package fr.dynamx.common.physics.terrain.element;

import fr.dynamx.common.physics.terrain.chunk.ChunkTerrain;
import fr.dynamx.common.physics.terrain.computing.TerrainCollisionsCalculator;

/**
 * {@link ChunkTerrain} element types
 */
public enum TerrainElementType
{
    /**
     * Both types
     */
    ALL,
    /**
     * Terrain generated by {@link TerrainCollisionsCalculator}
     */
    COMPUTED_TERRAIN,
    /**
     * Manually added terrain (see {@link fr.dynamx.common.physics.terrain.element.CustomSlopeTerrainElement})
     */
    PERSISTENT_ELEMENTS
}
