package fr.dynamx.core.common.physics.terrain.element;

import fr.dynamx.core.common.physics.terrain.chunk.ChunkTerrain;
import fr.dynamx.core.common.physics.terrain.computing.TerrainCollisionsCalculator;

/**
 * {@link ChunkTerrain} element types
 */
public enum TerrainElementType {
    /**
     * Both types
     */
    ALL,
    /**
     * Terrain generated by {@link TerrainCollisionsCalculator}
     */
    COMPUTED_TERRAIN,
    /**
     * Manually added terrain (see {@link CustomSlopeTerrainElement})
     */
    PERSISTENT_ELEMENTS,
    /**
     * Reload all types from start when an incorrect {@link fr.dynamx.api.physics.terrain.ITerrainElement} was found
     */
    RELOAD_ALL
}
